spring.application.name=reporte
<<<<<<< HEAD
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/dentify_reporte?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
=======
spring.datasource.url=jdbc:mysql://localhost:3306/dentify_reporte?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8089
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Habilitar Flyway
spring.flyway.enabled=true
# Ruta donde buscarás los scripts SQL
spring.flyway.locations=classpath:db/migration
# Importante si ya tienes datos en la BD y no quieres empezar de cero
spring.flyway.baseline-on-migrate=true
>>>>>>> 67fa270851138a6dc0b277d1edf3022863cc72e3
